### ISSUE TITLE
v0.1.0::PreRelease

### ISSUE THREAD

**Issue by nathanielBellamy** [nathanielBellamy/my_website#60]
# v0.1.0::PreRelease
- final touch ups and debugs

### TODO
- [x] Tab navigate home dropdown
- [x] git tag repo `git tag v0.1.0 -a` -> `gp --tags`
- [x] remove unused fonts
- [x] lfo translation translation fix
- [x] ensure any postponed work has a ticket in Todo
- [x] update ps epilepsy warning
- [x] control module width small screen
- [x] store settings
- [x] recaptcha failure modal
- [x] fix french translation on home about card
- [x] adjust prod `configuration.nix`
- [x] fix ep warning undefined
- [x] reorder emojis
- [x] move recaptcha
- [x] remove tab index from icons
- [x] fix lfo translation
- [x] add color index to msStore settings
- [x] left align verifying text on recaptcha modal
- [x] change modal bg to make it distinct from InfoGate
- [x] fix tab navigation on links
