### ISSUE TITLE
Feed Connection Status

### ISSUE THREAD

**Issue by nathanielBellamy** [nathanielBellamy/my_website#96]
# AC
- piggy back off of ui connection status

## TODO
- [x] `Feed` subscribes to `psConnected`
- [x] hide feed + emoji keyboard when disconnected
- [x] similar color changes to ms canvas border 
- [x] implement missing i18n or replace with icons
- [x] clear `psFeed` store on websocket close
- [x] flag system messages
- [x] allow client to format + `i18n` system messages

**Comment by nathanielBellamy** [comment]
🚀
